# -*- coding: utf-8 -*-
"""Image chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hvKBMCvGMqTSVMeGbImB74xRk8AmnWYb
"""

!pip install diffusers transformers accelerate torch
!pip install huggingface_hub
!pip install ipywidgets

!pip install diffusers transformers accelerate torch
!pip install huggingface_hub
!pip install ipywidgets

from diffusers import StableDiffusionPipeline
import torch

# Load the stable diffusion model
model_id = "runwayml/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

import ipywidgets as widgets
from IPython.display import display
from PIL import Image

# Function to generate images based on user input
def generate_image(prompt):
    image = pipe(prompt).images[0]
    display(image)

# Text input widget for user prompts
text_prompt = widgets.Text(
    value='',
    placeholder='Enter your image prompt here...',
    description='Prompt:',
    disabled=False
)

# Button widget to trigger image generation
generate_button = widgets.Button(
    description='Generate Image',
    disabled=False,
    button_style='',
    tooltip='Click to generate an image',
    icon='image'
)

# Function to handle button click event
def on_button_click(b):
    generate_image(text_prompt.value)

# Bind the button click event to the function
generate_button.on_click(on_button_click)

# Display the widgets
display(text_prompt, generate_button)

